name: waytrails
description: A route tracking app similar to Strava
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9

  # Map
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  # Location
  geolocator: ^11.0.0
  location: ^5.0.3

  # State Management
  provider: ^6.1.1

  # Backend
  supabase_flutter: ^2.3.4

  # Utils
  intl: ^0.19.0
  uuid: ^4.3.3
  shared_preferences: ^2.2.2

  # Env loader
  flutter_dotenv: ^5.0.2

  # For calling OpenStreetView APIs or other HTTP endpoints
  http: ^1.5.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
